### ISSUE TITLE
SemVer conventions

### ISSUE THREAD

**Issue by idmit** [mehcode/salt-rs#3]
Hi,

there is a [convention](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) to version numbers that precede 1.0 release.

If you don't use semantic versioning or want to do things another way in pre-release phase, then ignore this 😄 Just wanted to make sure you're aware of this convention.

**Comment by mehcode** [comment]
I don't consider `Salt` at a "initial development release" milestone yet. I feel confident in a good portion of the code but I want to expand on our example set as well as write at least a couple of small applications with it to get a "feel" for it. This will likely result in many small changes (and a couple major changes to middleware). When we move to `0.1.0` I'll also be committing to a deprecation cycle.
