### ISSUE TITLE
no method named mount found

### ISSUE THREAD

**Issue by nihiluis** [mehcode/salt-rs#4]
In the `hello.rs` example there is this snippet:

```rust
    let mut router = salt::router::Router::new();
    router.mount((Method::Get, "/", index));
    let mut service = Salt::new(router);
    service.run(":7878").unwrap();
```

I get a compiler error for it though and I'm unable to find it in the source.

Does it exist?

**Comment by mehcode** [comment]
@nihiluis Sorry for the confusion, that method was renamed `route` before I pushed `0.0.3`. I'll go update the example now.
